module.exports = {
  DB_CLIENT: 'pg',
  DB_HOST: '127.0.0.1',
  DB_PORT: '5432',
  DB_DATABASE: 'saas-starter',
  DB_USER: 'postgres',
  DB_PASSWORD: '',
  DB_SSL: 'false',
  RATE_LIMITER_ENABLED: false,
  RATE_LIMITER_STORE: 'memory',
  RATE_LIMITER_POINTS: 25,
  RATE_LIMITER_DURATION: 1,
  CACHE_ENABLED: false,
  STORAGE_LOCATIONS: 'local',
  STORAGE_LOCAL_DRIVER: 'local',
  STORAGE_LOCAL_ROOT: './uploads',
  KEY: '23cbe0f1-d4a6-4bc6-bede-17503c09381a',
  SECRET: '3oahLNNMAWf*q8wuutCP*7H^yM7$3UGmsV$z9WvaeUG8evoTMx^nvrYTwFS&kUtZw',
  REFRESH_TOKEN_COOKIE_NAME: 'saas_starter_refresh_token',
  EMAIL_FROM: 'no-reply@directus.io',
  EMAIL_TRANSPORT: 'sendmail',
  EMAIL_SENDMAIL_NEW_LINE: 'unix',
  EMAIL_SENDMAIL_PATH: '/usr/sbin/sendmail',
};
