version: 1
directus: 9.4.0
collections:
  - collection: posts
    meta:
      collection: posts
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: null
      group: null
      collapse: open
    schema:
      name: posts
      schema: public
      comment: null
fields:
  - collection: posts
    field: id
    type: integer
    schema:
      name: id
      table: posts
      data_type: integer
      default_value: nextval('posts_id_seq'::regclass)
      generation_expression: null
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_generated: false
      is_nullable: false
      is_unique: true
      is_primary_key: true
      has_auto_increment: true
      comment: null
      schema: public
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: posts
      field: id
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: true
      hidden: true
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: posts
    field: content
    type: text
    schema:
      name: content
      table: posts
      data_type: text
      default_value: null
      generation_expression: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_generated: false
      is_nullable: true
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      comment: null
      schema: public
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: posts
      field: content
      special: null
      interface: input-rich-text-html
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: true
      group: null
  - collection: posts
    field: Owner
    type: uuid
    schema:
      name: Owner
      table: posts
      data_type: uuid
      default_value: null
      generation_expression: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_generated: false
      is_nullable: false
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      comment: null
      schema: public
      foreign_key_schema: public
      foreign_key_table: directus_users
      foreign_key_column: id
    meta:
      collection: posts
      field: Owner
      special:
        - m2o
        - user-created
      interface: select-dropdown-m2o
      options:
        template: '{{email}}'
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: true
      group: null
relations:
  - collection: posts
    field: Owner
    related_collection: directus_users
    schema:
      table: posts
      column: Owner
      foreign_key_table: directus_users
      foreign_key_column: id
      foreign_key_schema: public
      constraint_name: posts_owner_foreign
      on_update: NO ACTION
      on_delete: SET NULL
    meta:
      many_collection: posts
      many_field: Owner
      one_collection: directus_users
      one_field: null
      one_collection_field: null
      one_allowed_collections: null
      junction_field: null
      sort_field: null
      one_deselect_action: nullify
