import { GraphQLClient } from 'graphql-request';
import config from '../../config';
import { getSdk } from './graphql/autogenerated/generated-sdk';

export const getHasuraSDK = (adminSecret?: string) =>
  getSdk(
    new GraphQLClient(config.hasura.graphQLURL, {
      headers: adminSecret
        ? {
            'x-hasura-admin-secret': adminSecret,
          }
        : undefined,
    })
  );

export type HasuraSDK = ReturnType<typeof getSdk>;
